version: '3.8'
services:
  mysql-nolu:
    image: mysql:latest
    container_name: mysql-nolu
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'capital'
      # MYSQL_USER: 'root'
      # MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    volumes:
      - mysqldata:/data/mysql
      
  app:
    build: .
    container_name: capitalization-v4 
    ports:
      - 3335:3335
    volumes:
      - .:/usr/app
    links: 
      - mysql-nolu
    depends_on:
      - mysql-nolu

volumes:
  mysqldata: